name: Auto-grading

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Check for README.md
      run: |
        if [ ! -f "README.md" ]; then
          echo "ERROR: README.md file is missing"
          exit 1
        fi
        
        if ! grep -q "http" README.md; then
          echo "WARNING: README.md might be missing a link to music recommendation"
        fi
    
    - name: Verify hash format
      run: |
        # Create a test email hasher script if it doesn't exist
        if [ ! -f "email_hasher.py" ]; then
          echo "ERROR: email_hasher.py file is missing"
          exit 1
        fi
        
        # Run the script with a test email
        python email_hasher.py "test@example.com"
        
        # Check if hash.email file exists
        if [ ! -f "hash.email" ]; then
          echo "ERROR: hash.email file was not created"
          exit 1
        fi
        
        # Read the hash and remove all whitespace
        HASH_OUTPUT=$(cat hash.email | tr -d '[:space:]')
        
        # Check hash length (should be 64 characters)
        if [ ${#HASH_OUTPUT} -ne 64 ]; then
          echo "ERROR: Hash length is not 64 characters (after removing whitespace)"
          exit 1
        fi
        
        # Check that all characters are valid hex digits
        if ! [[ $HASH_OUTPUT =~ ^[0-9a-fA-F]{64}$ ]]; then
          echo "ERROR: Hash contains non-hexadecimal characters"
          exit 1
        fi
        
        echo "Hash format verification passed" 